apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-app-1
  name: weather-app-1
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app-1
  template:
    metadata:
      labels:
        app: weather-app-1
    spec:
      containers:
        - image: registry.cosmin-lab.cloud:5000/weather-app:1
          imagePullPolicy: Always
          name: weather-app
      imagePullSecrets:
        - name: regcred2

---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-nodeport
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: weather-app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
      nodePort: 30001
