apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wather-app-5
  name: wather-app-5
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wather-app-5
  template:
    metadata:
      labels:
        app: wather-app-5
    spec:
      containers:
        - image: registry.cosmin-lab.cloud:5000/wather-app:5
          imagePullPolicy: Always
          name: wather-app
      imagePullSecrets:
        - name: regcred2

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb2
  name: myweb2
  namespace: jenkins
spec:
  ports:
  - nodePort: 30098
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb2
  type: NodePort