apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-app
  name: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: registry.cosmin-lab.cloud:5000/weather-app:1
          imagePullPolicy: Always
            imagePullSecrets:
        - name: regcred2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
