apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-app
  name: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: registry.cosmin-lab.cloud:5000/wather-app:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # Specificăm portul NodePort aici
  type: NodePort # Specificăm tipul serviciului ca fiind NodePort
