apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vreme
  name: vreme
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vreme
  template:
    metadata:
      labels:
        app: vreme
    spec:
      containers:
        - name: vreme
          image: registry.cosmin-lab.cloud:5000/vreme:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: vreme
  namespace: jenkins
spec:
  selector:
    app: vreme
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090 # Specificăm portul NodePort aici
  type: NodePort # Specificăm tipul serviciului ca fiind NodePort
